/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checkescrituras;

/**
 *
 * @author Henry
 */
public class checkList extends javax.swing.JFrame {
public String Tramitador, Telefono, nActa, Fecha, nombreEntrego, fechaEntrega, Firma;
    /**
     * Creates new form nuevo
     */
    public checkList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        cb5 = new javax.swing.JCheckBox();
        cb6 = new javax.swing.JCheckBox();
        cb7 = new javax.swing.JCheckBox();
        cb8 = new javax.swing.JCheckBox();
        cb9 = new javax.swing.JCheckBox();
        cb10 = new javax.swing.JCheckBox();
        cb11 = new javax.swing.JCheckBox();
        cb12 = new javax.swing.JCheckBox();
        cb13 = new javax.swing.JCheckBox();
        cb14 = new javax.swing.JCheckBox();
        jLabelTramitador = new javax.swing.JLabel();
        jTramitador = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTelefono = new javax.swing.JTextField();
        jLabelN_acta = new javax.swing.JLabel();
        jN_acta = new javax.swing.JTextField();
        jLabelFecha = new javax.swing.JLabel();
        jFecha = new javax.swing.JTextField();
        jLabelNombre_entrega = new javax.swing.JLabel();
        jNombre_entrega = new javax.swing.JTextField();
        jLabelFecha_entrega = new javax.swing.JLabel();
        jFecha_entrega = new javax.swing.JTextField();
        jLabelFirma = new javax.swing.JLabel();
        jFirma = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField3.setText("Henry efrain torres esquivel");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Teléfono:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonGuardar.setText("Guardar Datos");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Escrituras"));

        cb1.setText("IDENTIFICACIÓN DEL VENDEDOR(ES) (Y DE SU CÓNYUGE EN CASO DE ESTAR CASADOS EN SOCIEDAD CONYUGAL).");

        cb2.setText("IDENTIFICACIÓN DEL COMPRADOR(ES).");

        cb3.setText("ACTA DE NACIMIENTO PARA ACREDITAR EL PARENTESCO.");

        cb4.setText("ACTA DE MATRIMONIO DEL DONANTE (ES) Ó CERTIFICADO DE INEXISTENCIA DE MATRIMONIO – SOLTERÍA-.");

        cb5.setText("CÉDULA Y PLANOS ACTUALIZADOS.");
        cb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb5ActionPerformed(evt);
            }
        });

        cb6.setText("PATENTE DE ESCRITURA SIN CUANTÍA.");
        cb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb6ActionPerformed(evt);
            }
        });

        cb7.setText("PATENTE DE INSCRIPCIÓN");

        cb8.setText("LIBERTAD DE GRAVAMEN.");

        cb9.setText("CERTIFICADO DE NO ADEUDO DE PREDIAL.");

        cb10.setText("CERTIFICADO DE NO ADEUDAR COOPERACIÓN.");

        cb11.setText("CERTIFICADO DE NO ADEUDO DE AGUA O INEXISTENCIA DEL SERVICIO.");

        cb12.setText("ESCRITURA ANTERIOR. (PARA CONSTATAR SI NO HAY QUE PAGAR EL ISR YA QUE NO TODAS LAS DONACIONES ESTÁN EXENTAS).");
        cb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb12ActionPerformed(evt);
            }
        });

        cb13.setText("SOLICITUD DE EXENCIÓN PARA EL ISAI (DEJAR EN BLANCO EL NÚMERO DE ACTA Y LA FECHA DE LA ESCRITURA).");

        cb14.setText("AVALÚO.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cb1)
            .addComponent(cb2)
            .addComponent(cb3)
            .addComponent(cb4)
            .addComponent(cb5)
            .addComponent(cb6)
            .addComponent(cb7)
            .addComponent(cb8)
            .addComponent(cb9)
            .addComponent(cb10)
            .addComponent(cb11)
            .addComponent(cb13)
            .addComponent(cb14)
            .addComponent(cb12)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelTramitador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTramitador.setText("Tramitador:");

        jTramitador.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTramitador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTramitadorActionPerformed(evt);
            }
        });

        jLabelTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTelefono.setText("Teléfono:");

        jTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelefonoActionPerformed(evt);
            }
        });

        jLabelN_acta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelN_acta.setText("No. De Acta:");

        jN_acta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jN_acta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jN_actaActionPerformed(evt);
            }
        });

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelFecha.setText("Fecha:");

        jFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFechaActionPerformed(evt);
            }
        });

        jLabelNombre_entrega.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNombre_entrega.setText("Nombre de a quien se le entregó:");

        jNombre_entrega.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jNombre_entrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombre_entregaActionPerformed(evt);
            }
        });

        jLabelFecha_entrega.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelFecha_entrega.setText("Fecha de Entrega:");

        jFecha_entrega.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jFecha_entrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFecha_entregaActionPerformed(evt);
            }
        });

        jLabelFirma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelFirma.setText("Firma:");

        jFirma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jFirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirmaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNombre_entrega)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNombre_entrega))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTramitador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTramitador, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelN_acta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jN_acta, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelTelefono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFecha_entrega)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFecha_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabelFirma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFirma, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTramitador, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTramitador, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelN_acta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jN_acta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNombre_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFecha_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFirma, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFirma, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
        String mensaje="Las escrituras seleccionadas son: ";
        if(cb1.isSelected()){
            mensaje+="IDENTIFICACIÓN DEL VENDEDOR(ES) (Y DE SU CÓNYUGE EN CASO DE ESTAR CASADOS EN SOCIEDAD CONYUGAL).";
        }
        if(cb2.isSelected()){
            mensaje+="IDENTIFICACIÓN DEL COMPRADOR(ES).";
        }
        if(cb3.isSelected()){
            mensaje+="ACTA DE NACIMIENTO PARA ACREDITAR EL PARENTESCO.";
        }
        if(cb4.isSelected()){
            mensaje+="ACTA DE MATRIMONIO DEL DONANTE (ES) Ó CERTIFICADO DE INEXISTENCIA DE MATRIMONIO – SOLTERÍA-.";
        }
        if(cb5.isSelected()){
            mensaje+="CÉDULA Y PLANOS ACTUALIZADOS.";
        }
        if(cb6.isSelected()){
            mensaje+="PATENTE DE ESCRITURA SIN CUANTÍA.";
        }
        if(cb7.isSelected()){
            mensaje+="PATENTE DE INSCRIPCIÓN";
        }
        if(cb8.isSelected()){
            mensaje+="LIBERTAD DE GRAVAMEN.";
        }
        if(cb9.isSelected()){
            mensaje+="CERTIFICADO DE NO ADEUDO DE PREDIAL.";
        }
        if(cb10.isSelected()){
            mensaje+="CERTIFICADO DE NO ADEUDAR COOPERACIÓN.";
        }
        if(cb11.isSelected()){
            mensaje+="CERTIFICADO DE NO ADEUDO DE AGUA O INEXISTENCIA DEL SERVICIO.";
        }
        if(cb12.isSelected()){
            mensaje+="ESCRITURA ANTERIOR. (PARA CONSTATAR SI NO HAY QUE PAGAR EL ISR YA QUE NO TODAS LAS DONACIONES ESTÁN EXENTAS).";
        }
        if(cb13.isSelected()){
            mensaje+="SOLICITUD DE EXENCIÓN PARA EL ISAI (DEJAR EN BLANCO EL NÚMERO DE ACTA Y LA FECHA DE LA ESCRITURA).";
        }
        if(cb14.isSelected()){
            mensaje+="AVALÚO.";
        }
        Tramitador=jTramitador.getText();
        Telefono=jTelefono.getText();
        nActa=jN_acta.getText();
        Fecha=jFecha.getText();
        nombreEntrego=jNombre_entrega.getText();
        fechaEntrega=jFecha_entrega.getText();
        Firma=jFecha.getText();      
                
        //mostrarResultados.setText(mensaje);
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void cb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb5ActionPerformed

    private void cb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb6ActionPerformed

    private void cb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb12ActionPerformed

    private void jTramitadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTramitadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTramitadorActionPerformed

    private void jTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTelefonoActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jN_actaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jN_actaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jN_actaActionPerformed

    private void jFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFechaActionPerformed

    private void jNombre_entregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombre_entregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombre_entregaActionPerformed

    private void jFecha_entregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFecha_entregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFecha_entregaActionPerformed

    private void jFirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFirmaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb10;
    private javax.swing.JCheckBox cb11;
    private javax.swing.JCheckBox cb12;
    private javax.swing.JCheckBox cb13;
    private javax.swing.JCheckBox cb14;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JCheckBox cb5;
    private javax.swing.JCheckBox cb6;
    private javax.swing.JCheckBox cb7;
    private javax.swing.JCheckBox cb8;
    private javax.swing.JCheckBox cb9;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jFecha;
    private javax.swing.JTextField jFecha_entrega;
    private javax.swing.JTextField jFirma;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFecha_entrega;
    private javax.swing.JLabel jLabelFirma;
    private javax.swing.JLabel jLabelN_acta;
    private javax.swing.JLabel jLabelNombre_entrega;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTramitador;
    private javax.swing.JTextField jN_acta;
    private javax.swing.JTextField jNombre_entrega;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTelefono;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTramitador;
    // End of variables declaration//GEN-END:variables
}
